server:
  port: 8081

spring:
  application:
    name: keynote-service
  config:
    # C'est cette ligne qui corrige votre erreur :
    import: "optional:configserver:http://localhost:9999"

  # Configuration Base de donn√©es H2 (Locale)
  datasource:
    url: jdbc:h2:mem:keynote-db
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  # ... vos configs existantes (application name, datasource...) ...
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/sd-conference
          jwk-set-uri: http://localhost:8080/realms/sd-conference/protocol/openid-connect/certs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
